### ISSUE TITLE
error on docker compose files or missing instructions

### ISSUE THREAD

**Issue by Kazun3500** [apiman/apiman-docker#106]
Hello.

I have some problems to run docker compose with apiman and keycloak from this repository. As i understand i must to do some other things except execute "docker compose ..setup..." and "docker compose up " because docker-compose.yml file has strings like this "image: apiman/wildfly-manager:${project.version}" which causes error 
```
invalid interpolation format for services.apiman-gateway.image.
You may need to escape any $ with another $.
apiman/vertx-gateway:${project.version}
```
Also in this file exists bind directive to file "$PWD/data/apiman-keycloak-theme.jar"" which is missing.

**Comment by msavy** [comment]
You need to run mvn clean install first. You are looking at the development
branch. It has not been officially released yet.
