### ISSUE TITLE
Change http -> https

### ISSUE THREAD

**Issue by DevToanNH** [apiman/apiman-docker#17]
Can you update apiman-docker from http->https?
Example
http://cdn.rawgit.com/apiman/apiman-api-catalog/1.3.1.Final/catalog.json
-> https://cdn.rawgit.com/apiman/apiman-api-catalog/1.3.1.Final/catalog.json
plugin,...
Thanks you 👍

**Comment by msavy** [comment]
This is fixed in 1.3.2.Final

**Comment by msavy** [comment]
Resolved.
