### ISSUE TITLE
Сontainer not started

### ISSUE THREAD

**Issue by kolychev1995** [apiman/apiman-docker#18]
When I try to run the container with the command: docker run -it -p 58082:8082 --name APIMan-Vertx -v $PWD/examples/apis:/opt/apiman/apis -v $PWD/examples/configs:/opt/apiman/configs apiman/vertx-standalone sample.yml

I do not understand where to get the file all.json
The image was built in Windows. The version of Docker: 18.03.1-ce
Then the container started in Linux. The version of Docker: 1.13.1

I get:
```INFO  Loaded declaration: /opt/apiman/apis/sample.yml
INFO  A plugin has been specified without a friendly name. References must be by its full coordinates: io.apiman.plugins:apiman-plugins-test-policy:1.3.1.Final:war
ERROR Error applying declaration: java.nio.file.AccessDeniedException: /opt/apiman/apis/all.json
Usage: apiman-cli gateway generate headless [--debug] [--declarationFile, -f] [--help, -h] [--outputFile, -o] [--propertiesFile] [--stdout] [--waitTime, -w] [-P]
The following arguments are available:

   --debug: Log at DEBUG level
   --declarationFile, -f: Declaration file
   --help, -h: Display usage only
   --outputFile, -o: Output file(s) or directory. If a directory is provided a filename will be generated. [default: []]
   --propertiesFile: Properties file
   --stdout: Output definition to STDOUT (implied if no outputFile is specified)
   --waitTime, -w: Server startup wait time (seconds) [default: 0]
   -P: Set property (key=value)

**Comment by kolychev1995** [comment]
I'm trying to run the apiman vertx standalone container.

**Comment by msavy** [comment]
@pcornish what's your recommended way of providing a customised JSON conf file? I see CONFIG_FILE_PATH. Don't want to try to give advice that's contradictory to your best practices.

https://github.com/apiman/apiman-docker/blob/master/vertx-standalone/files/docker-entrypoint.sh

**Comment by msavy** [comment]
Sorry, meant to tag in @outofcoffee

**Comment by volkflo** [comment]
I will close this now.
@kolychev1995 If you have still issues with this, please reopen this issue or create a new one :)
