### ISSUE TITLE
apiman/vertx-standalone on Docker hub

### ISSUE THREAD

**Issue by copitz** [apiman/apiman-docker#19]
Hi,

in the [docs of the vertx standalone](https://github.com/apiman/apiman-docker/tree/master/vertx-standalone) it says that the image is on docker hub but its not. Is this for a particular reason like that its just not meant to be used yet or is it just missing?

Thank you very much,
Christian

**Comment by msavy** [comment]
Ah, I think it's just a mistake that it must not have been pushed. @pcornish any thoughts, or you ok with me publishing it? I can add you to the org if you like.

**Comment by copitz** [comment]
Ah, thank you - I just saw that the same applies for the cli image. Did you mean me to add to the org? If yes, sure :)

**Comment by msavy** [comment]
Sorry, I meant to tag in @outofcoffee, as he's the original author of the image.

**Comment by copitz** [comment]
Hi, is there any progress on that?

**Comment by volkflo** [comment]
@EricWittmann What do you think about publishing the standalone image as well? I think shouldn't be much effort.

**Comment by EricWittmann** [comment]
Works for me.  Shouldn't be much effort at all, assuming it still builds OK. :)

**Comment by volkflo** [comment]
We will provide updated images on dockerhub / ghcr soon!

**Comment by msavy** [comment]
I believe I've done this now.

Should be on DockerHub and GHCR
