### ISSUE TITLE
HTTPS on a remote server

### ISSUE THREAD

**Issue by fabienmifsud** [apiman/apiman-docker#21]
Hi,
I'm trying to connect my localhost app to apiMan & its embedded keycloak installed as a docker on a remote server.
I can't connect to apiman/keycloak through http because it is not accessed locally. I'm now trying to connect through https but the self-signed certificate of apiman/keycloak is associated to "localhost" domain instead of its hosting server. That causes the ssl handshake to fail because the certificate is provided for "localhost" instead of the server domain name.
How can I tell apiman/keycloak inside the container that they are running and accessed on a remote server ?
thx

**Comment by EricWittmann** [comment]
Hm - I think the best you **might** be able to do is disable cert validation so that the SSL handshake doesn't fail even though the host doesn't match the cert.  I don't recall if apiman has a way to do that offhand.  @msavy any idea?

**Comment by volkflo** [comment]
I think we can close this.
@fabienmifsud if this is still a problem or not solved in the current version of apiman, please reopen this issue :)
