### ISSUE TITLE
Docker image build failed for 1.5.1.Final

### ISSUE THREAD

**Issue by sjugge** [apiman/apiman-docker#22]
## Problem

According to [the download docs](http://www.apiman.io/latest/download.html), version 1.5.1.Final is available as Docker image.

However, this tag is missing from the Docker Hub, see:

* https://hub.docker.com/r/apiman/on-wildfly11/tags/
* https://hub.docker.com/r/apiman/on-wildfly10/tags/

It would seem that the builds on Docker Hub failed:

* [apiman/on-wildfly10](https://hub.docker.com/r/apiman/on-wildfly10/builds/bsmhemvsy5raaurtphrqiyg/)
* [apiman/on-wildfly11](https://hub.docker.com/r/apiman/on-wildfly11/builds/bcrxx22jeekhmqc6lbacmtq/)

Both failed with the following message:

```
warning: Could not find remote branch 1.5.1.Final to clone.

fatal: Remote branch 1.5.1.Final not found in upstream origin

please ensure the remote branch exists (128)
```

## Expected behaviour

Docker image for the 1.5.1.Final release is available on Docker Hub as per documentation.

**Comment by msavy** [comment]
Thanks. I’m not sure why this is happening. I’ve tried rebuilding but the same error happens; the tag is definitely there in the repo, so not sure why it can’t find it.

**Comment by sjugge** [comment]
> fatal: Remote branch 1.5.1.Final not found in upstream origin

It seems to build from **branch**, not **tag**. In this repo no branch by that name exists.

**Comment by sjugge** [comment]
Another odd observation.

**Docker hub**

Last build on `master` is from a day ago:

* https://hub.docker.com/r/apiman/on-wildfly10/tags/
* https://hub.docker.com/r/apiman/on-wildfly11/tags/

**GitHub**

Last `master` branch commit is from July 25th:

* https://github.com/apiman/apiman-docker/commits/master

**Comment by msavy** [comment]
The master builds are from apiman/apiman master, not apiman/apiman-docker master

I think the tag error is misleading, and just says branch when it can’t find a tag.

**Comment by msavy** [comment]
Should be fixed now. Let’s see.

**Comment by sjugge** [comment]
Build error unfortunately.

```
warning: Could not find remote branch 1.5.1.Final to clone.

fatal: Remote branch 1.5.1.Final not found in upstream origin

please ensure the remote branch exists (128)
```

**Comment by sjugge** [comment]
For now, I'm unblocked as `latest` contains `1.5.1.Final`. But a properly tagged image would be great of course.

**Comment by msavy** [comment]
Okay, think it's working now. Was my fault, I hadn't pushed the 1.5.1.Final tag.

**Comment by sjugge** [comment]
Yup, build was successful!

Thanks for the fast follow-up on this @msavy, appreciate it!
