### ISSUE TITLE
Missing docker image: apiman/on-wildfly11:1.5.3.Final

### ISSUE THREAD

**Issue by geertschuring** [apiman/apiman-docker#23]
The instructions on the website mention a docker image that does not seem to exist on docker hub:

> D:\>docker pull apiman/on-wildfly11:1.5.3.Final
> Error response from daemon: manifest for apiman/on-wildfly11:1.5.3.Final not found: manifest unknown: manifest unknown

**Comment by EricWittmann** [comment]
You're right - my release script failed for the docker images.  I'm uploading them now.  Thanks!
