### ISSUE TITLE
Only keep most recent version of wildfly?

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman-docker#28]
@EricWittmann As I asked in the other [issue ](https://github.com/apiman/apiman/issues/766#issuecomment-673287804) maybe it would be good to remove one version of wildfly and only keep the latest version.

This will probably decrease the maintenance effort.

Because we do everything in docker we may assist you but our resources are also very limited :(

**Comment by EricWittmann** [comment]
I'll definitely be doing that here.  It's only problematic for the distro itself (in the main codebase) because of the EAP7->Wildfly10 dependency.

**Comment by volkflo** [comment]
I close this because this is already done
