### ISSUE TITLE
Docker images missing/out of date for 1.2.x

### ISSUE THREAD

**Issue by outofcoffee** [apiman/apiman-docker#5]
Hi @EricWittmann, following the merge of these PRs:

* https://github.com/apiman/apiman-docker/pull/3
* https://github.com/apiman/apiman-docker/pull/4

...the Docker images for 1.2.1 are not yet in Docker Hub.

```
$ docker run -it -p 8080:8080 -p 8443:8443 jboss/apiman-wildfly:1.2.1.Final
Unable to find image 'jboss/apiman-wildfly:1.2.1.Final' locally
Pulling repository docker.io/jboss/apiman-wildfly
Tag 1.2.1.Final not found in repository docker.io/jboss/apiman-wildfly
```

Are we able to push these to Docker Hub?

## Current state
* The apiman wildfly8 image is still pointing to 1.1.1: https://hub.docker.com/r/apiman/on-wildfly8/~/dockerfile/
* The jboss one is on 1.1.9: https://hub.docker.com/r/jboss/apiman-wildfly/~/dockerfile/
* There's no wildfly9 one yet: https://hub.docker.com/u/apiman/

**Comment by EricWittmann** [comment]
I can't push the jboss images to docker hub, but I can push the apiman ones.  I'll do that on Monday (I don't have access to my workstation ATM).  Kick me if I forget to do it. :)

Note: originally we had the apiman/on-wildfly8 image, but were then encouraged to drop that in favor of the jboss images.  Unfortunately my pull requests to the jboss docker repo tend to languish for a long time.  So I think I'm going to move us back to the apiman/on-* images and update the project site accordingly.

**Comment by hkeeler** [comment]
Also, there's reference to a `apiman/on-wildfly10` Docker repo in a few places:

* https://github.com/apiman/apiman-docker/tree/master/on-wildfly10#image-accessible-on-docker-hub
* http://www.apiman.io/latest/download.html

...but it doesn't seem to exist.  I only see on-wildfly8 and on-wildfly9 at https://hub.docker.com/r/apiman/.

It looks like the [`Dockerfile`](https://github.com/apiman/apiman-docker/blob/master/on-wildfly10/Dockerfile) is good to go, just needs to be pushed up.

**Comment by EricWittmann** [comment]
Thanks for the report.  I clearly don't use Docker Hub enough to make it do what I want.  :)  I believe I've updated it and automated builds should be underway now.  I imagine that by the end of the day today everything will be built and available (I hope!).

**Comment by hkeeler** [comment]
Awesome.  Confirmed a `docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly10` now works.  Thanks!

**Comment by EricWittmann** [comment]
Welcome!
