### ISSUE TITLE
Persistent apiman/on-wildfly

### ISSUE THREAD

**Issue by paoloaq** [apiman/apiman-docker#53]
Hello everyone, 
first of all thank you for the great job done with APIMAN!

Is there an easy way (volumes?) to make the `apiman/on-wildfly` version persistent?
At each container reboot all the Keycloak and APIMAN configurations are lost.

Thank you so much

**Comment by volkflo** [comment]
Hi @paoloaq,

please try to mount the path `/opt/jboss/wildfly/standalone/data` into a volume.
Per default, the data should not be lost during reboot but on container recreate.

Please note that this docker image should not be used for production setups.
We will provide a more stable docker-compose configuration shortly.

**Comment by msavy** [comment]
(Might also be worth testing out the pull request if you want to provide feedback -- https://github.com/apiman/apiman-docker/pull/46)

**Comment by paoloaq** [comment]
> Hi @paoloaq,
> 
> please try to mount the path `/opt/jboss/wildfly/standalone/data` into a volume of your choice. Per default, the data should not be lost during a reboot but on container recreate.
> 
> Please note that this docker image should not be used for production setups. We will provide a more stable docker-compose configuration shortly.

Sorry, my fault! I use Docker Swarm and I didn't know it recreates containers after rebooting the node.

Since I need the swarm I tried to mount a volume for the folder `/opt/jboss/wildfly/standalone/data`: `docker run -v /home/username/apiman_volume:/opt/jboss/wildfly/standalone/data -it -p 8443:8443 apiman/on-wildfly`

However the JBoss exception is thrown:
```
java.lang.IllegalStateException: WFLYSRV0126: Could not create server content directory: /opt/jboss/wildfly/standalone/data/content
		at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:482)
		at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.Main.determineEnvironment(Main.java:388)
		at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.Main.main(Main.java:96)
		at org.jboss.modules.Module.run(Module.java:352)
		at org.jboss.modules.Module.run(Module.java:320)
		at org.jboss.modules.Main.main(Main.java:617)
	15:21:08,228 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
```

I tried deleting [the command `USER jboss` from the Dockerfile](https://github.com/apiman/apiman-docker/blob/3c9a4d81cd8026f950c74a412811080d37776a50/on-wildfly/Dockerfile#L17) and it works.
Is it dangerous to start JBoss as root? If so, do you think there may be some alternative to using the volume without getting the error?

Thanks a lot!


> (Might also be worth testing out the pull request if you want to provide feedback -- #46)

I will definitely try as soon as I can. Thank you!

**Comment by paoloaq** [comment]
Hi, solved the JBoss exception by setting chmod on the host's volume folder.
Thanks!

**Comment by msavy** [comment]
Thanks for sharing your solution to benefit others who might encounter the same scenario 👍
