### ISSUE TITLE
Incorrect Dockerfile for wildfly-manager ?

### ISSUE THREAD

**Issue by ncasaux** [apiman/apiman-docker#56]
Hello!

When I simply run `docker run -it -p 8443:8443 apiman/wildfly-manager`, I have errors related to the datasource:

`09:57:26,880 ERROR [stderr] (Thread-125) Caused by: javax.naming.NameNotFoundException: datasources/apiman-manager -- service jboss.naming.context.java.jboss.datasources.apiman-manager`

I think it could be related to the fact that the apiman-ds.xml file is removed in the [Dockerfile](https://github.com/apiman/apiman-docker/blob/master/wildfly-manager/Dockerfile):
`rm -rf $JBOSS_HOME/standalone/deployments/apiman-ds.xml && \`

Is that a mistake ? If yes, I can create a PR to fix this.
Thanks!

**Comment by volkflo** [comment]
Hi @ncasaux.

thanks for opening this issue and the interest in our docker images.

Unfortunately, the current docker images are not totally ready to use.
We are currently working on some changes in the main project to get the `on-wildfly` image working.
The `on-tomcat` images should work already.

Please note:
All images are currently flagged as latest.
Once they are ready we will release them with the same version tag as apiman and also release an updated docker-compose for the whole apiman setup (including db, keycloak and devportal)

**Comment by ncasaux** [comment]
Thanks for your reply @volkflo 

Actually I thought the images labelled as "Production grade" were ready to use, and to be honest, I managed to have a complete and successfull containerized setup with postgres, keycloak, wildfy-manager, vertx-gateway, elasticsearch, all wired together. I had to do some minor ajustements though...

I plan to have a similar installation on production in a few months! 😃

**Comment by msavy** [comment]
@ncasaux would you be willing to make some contributions to the docker project from what you have learned? That would help the project a lot.

**Comment by msavy** [comment]
This should be fixed now (by me/my company) @ncasaux .

I would still greatly appreciate if you could make some contributions, though, from what you have learned...

**Comment by ncasaux** [comment]
Hello @msavy ,

At that time, I managed to have a wildfly manager + wildfly gateway + keycloak + elasticsearch + postgres. From what I see in the docker files, the gateway on wilfdly is not a thing anymore ? 
On what topic would you like me to have a look ?

**Comment by msavy** [comment]
I'm not aware that any images have been deleted. The "on-wildfly" image
still should be published, which includes the WildFly gateway.
