### ISSUE TITLE
Docker-Image needs root rights

### ISSUE THREAD

**Issue by thomas-siegrist** [apiman/apiman-docker#6]
It seems like the given docker-image needs root rights in order to run properly. In our openshift-cluster we restrict per default root rights. When I run the tocker-image, I get an error, that a directory does not exist. When I start the Image in openshift with root-privileges, it boots-up without an error.

I would expect, that the Image can run without root rights.

**Comment by lucamaf** [comment]
same issue here with Openshift Origin v.1.5.0

**Comment by msavy** [comment]
Thanks for the report. 

According to @mijaros it's because we're using UIDs where we should be using groups. Will look into it and see if we can fix it ASAP.

**Comment by msavy** [comment]
Hi, @lucamaf and @thomas-siegrist can you test out PR #8? It seems to work OK now, but I'd like someone to verify it.

**Comment by msavy** [comment]
Also @mijaros if you can test this at some point that'd be great :)

**Comment by mijaros** [comment]
@msavy Tried it, and it is working :)

**Comment by msavy** [comment]
Fantastic. Thanks, Miro!

**Comment by msavy** [comment]
@thomas-siegrist @lucamaf  The Docker builds are complete. Use the `latest` tag.

**Comment by thomas-siegrist** [comment]
Thanks! It works fine now.

**Comment by msavy** [comment]
Cheers to @jmtd for the tips
